import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Mainsection from './mainsection'
import Announcements from './announcements'
import Testing from './testing'
import Offices from './offices'
import Helpdesk from './helpdesk'
import Accordion from '../components/accordion'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NEU VLE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/neulogo.png" />
      </Head>
      <Navbar/>
      <Mainsection/>
      <Announcements/> 
      <Offices/>
      <Accordion title="Click Me!" content="this is content 1" />
      
    </div>
  )
}
